# Generated by Django 4.2.15 on 2024-08-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_customuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pin_code',
        ),
    ]
