# Generated by Django 4.2.15 on 2024-08-18 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('entity_type', models.CharField(max_length=20)),
                ('incident_details', models.TextField()),
                ('reported_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
